# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: dshaneg/nodejs:8-alpine

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint
      - run: yarn tsc
      - run: yarn test
      - run: mkdir -p target/dist && yarn pack && mv *.tgz target/dist

      - persist_to_workspace:
          root: target
          paths: dist

      - store_artifacts:
          path: target/dist

  publish:
    docker:
      - image: dshaneg/nodejs:8-alpine

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Set npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Establish git host
          command: |
            set +e
            ssh -T -o StrictHostKeyChecking=no git@github.com
            echo "github always makes ssh exit with non-zero, so echoing for 0 exit code"
      - run:
          name: Publish to NPM
          command: npm publish dist/*.tgz


workflows:
  version: 2
  build-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      # - approve:
      #     type: approval
      #     requires:
      #       - build
      #     filters:
      #       tags:
      #         only: /v[0-9]+(\.[0-9]+)*/
      #       branches:
      #         ignore: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+){0,2}(-..*)*/
            branches:
              ignore: /.*/
