# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: dshaneg/nodejs:8-alpine

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: mkdir -p target/test-results/unit-tests

      - run:
          command: make build
          environment:
            MOCHA_FILE: target/test-results/unit-tests/test-results.xml

      - store_test_results:
          path: target/test-results

      - persist_to_workspace:
          root: .
          paths:
            - target/dist
            - Makefile
            - bin

      - store_artifacts:
          path: target

  publish:
    docker:
      - image: dshaneg/nodejs:8-alpine

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Publish to NPM
          command: make publish


workflows:
  version: 2
  build-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+){0,2}(-..*)*/
            branches:
              ignore: /.*/
