# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: dshaneg/nodejs:8-alpine

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint
      - run: yarn test
      - run: yarn tsc
      - run: yarn pack

      - store_artifacts:
          path: test-adventure-core-$CIRCLE_TAG.tgz

  publish:
    docker:
      - image: dshaneg/nodejs:8-alpine

    steps:
      - run: ls -l
      - run:
          name: Set npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc


workflows:
  version: 2
  build-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      # - approve:
      #     type: approval
      #     requires:
      #       - build
      #     filters:
      #       tags:
      #         only: /v[0-9]+(\.[0-9]+)*/
      #       branches:
      #         ignore: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
